 name: shell Commands

 on: [push]

 jobs: 
  run-shell-command:
    runs-on: macos-latest
    steps: 
      - name: exho a string
        run: echo "hello world this is 2nd commit"
      - name: multiline script
        run: |
          node -v
          npm -v
